
---
- name: Creating a file
  hosts: webserver
  become: true
  tasks:
  - name: create a file
    file:
      path: /var/www/html/index.html
      state: touch
    
  - name: content in file
    lineinfile:
      path: /var/www/html/index.html
      line: WEB test successful
      state: present  
