---
- name:  just a test
  hosts: all
  tasks:
    - name: install a maria-db server if enough space on root
      yum:
        name: mariadb-server
        state: latest
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/" and item.size_available > 300000000

