---
- name: Task Failure Exercise
  hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb
  tasks:
  - name: installation of packages
    block:
    - name:  installed {{ web_package }}
      yum:
        name: "{{ web_package }}"
        state: latest
       
       
    rescue:
    - name: installed {{ db_package }}
      yum:
        name: "{{ db_package }}"
        state: latest
    
    always:
    - name: start db
      service:
        name: "{{ db_service }}"
        state: started
        enabled: true
