---
- name: copy module prac
  hosts: all
  remote_user: devops
  become: true
  tasks:
  - name: copy
    copy:
      src: files/users.txt
      dest: /home/devops/users.txt
      owner: devops
      group: devops
      mode: u+rw,g-wx,o-rwx
      setype: samba_share_t
