- name: blocking
  block:
  - name: delivering template 
    template:
      src: templates/hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: output
    notify: NetworkManager restart
  
- name: rescue module
  rescue: 
  - name: revert to old file
    copy:
      src: "{{ output.backup_file }}"
      dest: /etc/hosts
      remote_src: yes
  always:
  - name: reload NetworkManager
    service:
      name: NetworkManager
      state: restarted
